### ISSUE TITLE
Won't build with OpenFOAM 2.4.0

### ISSUE THREAD

**Issue by petebachant** [wyldckat/wallShearStressLES#1]
I can try to fix this up later, but want to note this for now.

Errors:

```bash
could not open file cyclicAMILduInterface.H for source file wallShearStressLES.C due to No such file or directory
could not open file cyclicAMIPolyPatch.H for source file wallShearStressLES.C due to No such file or directory
OpenFOAM/OpenFOAM-2.4.0/src/finiteVolume/lnInclude/cyclicAMIFvPatch.H:39:35: fatal error: cyclicAMILduInterface.H: No such file or directory
 #include "cyclicAMILduInterface.H"
                                   ^
```

**Comment by wyldckat** [comment]
Many thanks! Same happens on 2.3.x. I'll try to push an update soon.

**Comment by wyldckat** [comment]
Fixed in commit fd73cf7ad6a166f86ee049bb3308e62ab0b4d38a.

**Comment by petebachant** [comment]
Works like a charm. Thanks Bruno!
